### PR TITLE
Image sizes not available for new entries

### PR DESCRIPTION
**Pull request by nathanpitman**
Fixes bug where you were unable to pick from image sizes for the specified upload directory when adding a new entry.

### CODE REVIEW

**Comment by mvarga** [comment]
Hi nathanpitman, 
i have set write access for EE_Field_Pack repository.

Thank you for your issues again.

**Comment by nathanpitman** [comment]
Thanks Michal, do you mind if I re-organise the folder structure of the repo to separate the various fields and modules living in it so it's clearer for users?

**Comment by nathanpitman** [comment]
To clarify, ideally the 'Promotions' module would reside in it's own repo. :)

**Comment by peterfelix** [comment]
Hi Nathan,

sure, feel free to re-organize it the way you prefer :)

Thanks,
Peter

**Comment by nathanpitman** [comment]
Any chance you could create a separate repo for 'Promotions Module' for me and assign me to that so I can move that out of the field pack repo? I don't have permission to add repos. :)

**Comment by peterfelix** [comment]
Hi Nathan,

sure, please check this: https://github.com/krea/EE_Promotions

Thanks,
Peter

**Pull request merged**
